FROM jupyter/base-notebook:latest

######## Install base software
USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        git curl && \
    rm -rf /var/lib/apt/lists/*

######## Set up user environment
ENV HOME=/home/jovyan
ENV WORK=${HOME}/work
ENV MPLCONFIGDIR="${HOME}/.cache/matplotlib"
ENV PYTHONPATH="${WORK}/jgi_integration"
RUN mkdir -p ${WORK} ${HOME}/.cache/matplotlib ${HOME}/.cache/uv && \
    chown -R jovyan:users ${WORK} ${HOME}/.cache

######## Start as jovyan
USER jovyan
WORKDIR ${WORK}

######## Copy local files into the container for development
COPY venv/pyproject.toml venv/uv.lock ${WORK}
#COPY notebooks/integration_workflow.ipynb ${WORK}
COPY docker/jupyter_server_config.py ${HOME}/.jupyter/jupyter_server_config.py

######## Install uv
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="${HOME}/.local/bin:${PATH}"

######## Set up software environment with uv
RUN uv sync --locked
ENV VIRTUAL_ENV=${WORK}/.venv
ENV PATH="${VIRTUAL_ENV}/bin:${PATH}"

######## Set up user workflow environment
RUN python -m ipykernel install --user \
    --name=jgi-integration \
    --display-name="JGI Integration"

######## Ensure proper permissions after setting up container
USER root
RUN chown -R jovyan:users ${HOME}
USER jovyan