# This configuration file is used to set up a multi-omics data integration project.
# It includes user settings, dataset configurations, analysis parameters, and project metadata.
# Details on each section and parameters can be found in the workflow documentation at
# https://github.com/bkieft-usa/jgi_integration/tree/main/docs or within the JupyterLab environment
# in the /jgi_integration/docs folder.

# NOTE: Parameters with XXX should not be changed

user_settings:
  project_name: Cvetkovska_508469_Chlamydomonas
  variable_list:
    - salinity
    - light
    - condition
    - group # XXX

datasets:
  data_processing_tag: DEFAULT
  tx:
    dataset_dir: transcriptomics # XXX
    normalization_parameters:
      filtering:
        method: minimum
        value: 100
      devariancing:
        method: percent
        value: 20
      scaling:
        log2: true
        method: modified_zscore
      replicate_handling:
        method: variance
        group: group
        value: 0.5
  mx:
    dataset_dir: metabolomics # XXX
    chromatography: HILIC
    polarity: multipolarity
    normalization_parameters:
      filtering:
        method: minimum
        value: 100000
      devariancing:
        method: percent
        value: 20
      scaling:
        log2: true
        method: modified_zscore
      replicate_handling:
        method: variance
        group: group
        value: 0.5

analysis:
  data_analysis_tag: DEFAULT
  analysis_parameters:
    feature_selection:
      selected_method: random_forest
      max_features: 10000
      variance:
        top_n: 5000
      glm:
        category:
        reference:
        significance_level: 0.05
        log2fc_cutoff: 0.25
      kruskalwallis:
        category:
        significance_level: 0.05
        lfc_cutoff: 0.5
      feature_list:
        feature_list_file:
      lasso:
        category:
      random_forest:
        category: salinity
      mutual_info:
        category:
    correlation:
      corr_method: pearson
      corr_cutoff: 0.75
      keep_negative: false
      block_size: 500
      cores: -1
      corr_mode: bipartite
    networking:
      submodule_mode: louvain
      wgcna_params:
        beta: 12
        min_module_size: 3
        distance_cutoff: 0.002
      interactive_plot: true
      interactive_layout: spring
    functional_enrichment:
      annotation_column: tx_goterm_acc
      pvalue_cutoff: 0.05
      min_genes_per_term: 1
      correction_method: fdr_bh
    mofa:
      num_mofa_factors: 5
      num_mofa_iterations: 1000
      seed_for_training: 555

# Settings are not configurable beyond this point
project:
  dataset_list:
    - tx # XXX
    - mx # XXX
  PI_name: Cvetkovska # XXX
  proposal_ID: 508469 # XXX
  results_path: /home/jovyan/work/output_data # XXX
  raw_data_path: /home/jovyan/work/input_data/raw_data # XXX
  metadata_link: /home/jovyan/work/input_data/link_script/metadata_link_script.py # XXX
